"""add is_muted and forum_posts

Revision ID: 606e15fed784
Revises: 9622447fbb88
Create Date: 2026-03-27 15:47:04.469871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606e15fed784'
down_revision: Union[str, None] = '9622447fbb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Note: is_musician, is_active, is_banned, invite_code columns already exist
    # op.add_column('users', sa.Column('is_musician', sa.Boolean(), nullable=False))
    # op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_muted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # op.add_column('users', sa.Column('invite_code', sa.String(length=32), nullable=True))
    # op.alter_column('users', 'is_admin',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'is_admin',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    # op.drop_column('users', 'invite_code')
    op.drop_column('users', 'is_muted')
    # op.drop_column('users', 'is_banned')
    # op.drop_column('users', 'is_active')
    # op.drop_column('users', 'is_musician')
    op.drop_table('forum_posts')
    # ### end Alembic commands ###
